# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mess_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess_type', models.CharField(max_length=100)),
                ('veg_thali_prize_per_thali', models.IntegerField()),
            ],
        ),
    ]
