# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostYourFoodAd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mess_info',
            name='nonveg_thali_prize_per_month_both_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mess_info',
            name='nonveg_thali_prize_per_month_one_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mess_info',
            name='nonveg_thali_prize_per_thali',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mess_info',
            name='veg_thali_prize_per_month_both_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mess_info',
            name='veg_thali_prize_per_month_one_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mess_info',
            name='veg_thali_prize_per_thali',
            field=models.IntegerField(default=0),
        ),
    ]
