# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 12:32
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAdministrator', '0002_auto_20170328_2311'),
        ('PostYourFoodAd', '0002_auto_20170422_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thali_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetable', models.IntegerField(default=1)),
                ('roti', models.IntegerField(default=1)),
                ('dal', models.IntegerField(default=1)),
                ('rice', models.IntegerField(default=1)),
                ('salad', models.CharField(default='some string', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='mess_info',
            name='address',
            field=models.CharField(default='some string', max_length=200),
        ),
        migrations.AddField(
            model_name='mess_info',
            name='description',
            field=models.CharField(default='some string', max_length=500),
        ),
        migrations.AddField(
            model_name='mess_info',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='mess_info',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mess', to='UserAdministrator.UserInfo'),
        ),
        migrations.AddField(
            model_name='thali_details',
            name='thali_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='thali_details', to='PostYourFoodAd.Mess_Info'),
        ),
    ]
