# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostYourFoodAd', '0004_mess_info_mess_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mess_info',
            name='mess_type',
            field=models.CharField(choices=[('V', 'VEG'), ('N', 'NONVEG'), ('VN', 'VEG_NONVEG')], max_length=100),
        ),
    ]
