# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAdministrator', '0002_auto_20170328_2311'),
        ('PostYourAd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotbasisrooms',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UserAdministrator.UserInfo'),
        ),
    ]
