# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAdministrator', '0002_auto_20170328_2311'),
        ('PostYourAd', '0002_cotbasisrooms_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatOnRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_type', models.CharField(max_length=100)),
                ('furnishing_type', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='UserAdministrator.UserInfo')),
            ],
        ),
        migrations.AlterField(
            model_name='cotbasisrooms',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='UserAdministrator.UserInfo'),
        ),
    ]
