# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostYourAd', '0004_auto_20170401_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotbasisrooms',
            name='deposite',
            field=models.IntegerField(null=True),
        ),
    ]
