# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostYourAd', '0006_cotbasisrooms_room_rent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotbasisrooms',
            name='room_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
