# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostYourAd', '0008_cotbasisrooms_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotbasisrooms',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
