# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostYourAd', '0009_cotbasisrooms_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_Amanities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='cotbasisrooms',
            name='amenities',
            field=models.ManyToManyField(to='PostYourAd.Room_Amanities'),
        ),
    ]
