# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostYourAd', '0011_cotbasisrooms_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatonrent',
            name='flat_rent',
            field=models.IntegerField(default=0),
        ),
    ]
