# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostYourAd', '0013_flatonrent_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatonrent',
            name='address',
            field=models.CharField(default=b'some string', max_length=200),
        ),
    ]
