# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostYourAd', '0014_flatonrent_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatonrent',
            name='no_of_persons_allowed',
            field=models.IntegerField(default=1),
        ),
    ]
