# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostYourAd', '0015_flatonrent_no_of_persons_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatonrent',
            name='description',
            field=models.CharField(default=b'some string', max_length=500),
        ),
    ]
