# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostYourAd', '0017_flatonrent_maintainance_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatonrent',
            name='floor_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flatonrent',
            name='lift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flatonrent',
            name='no_of_balconies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flatonrent',
            name='no_of_bathrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flatonrent',
            name='total_floor',
            field=models.IntegerField(default=1),
        ),
    ]
