# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 17:32
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostYourAd', '0018_auto_20170419_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatonrent',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
