# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PostYourAd', '0020_flat_furnishing_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat_furnishing_details',
            name='furnishing_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furnitures', to='PostYourAd.FlatOnRent'),
        ),
    ]
