# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostYourAd', '0022_auto_20170420_1641'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flat_Furnishing_Details',
            new_name='Flat_Images_Details',
        ),
    ]
