# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostYourAd', '0023_auto_20170420_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat_Furnishing_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='flatonrent',
            name='furnishing_details',
            field=models.ManyToManyField(to='PostYourAd.Flat_Furnishing_Details'),
        ),
    ]
