# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostYourAd', '0024_auto_20170421_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotbasisrooms',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='PostYourAd.Room_Amanities'),
        ),
        migrations.AlterField(
            model_name='flatonrent',
            name='furnishing_details',
            field=models.ManyToManyField(blank=True, to='PostYourAd.Flat_Furnishing_Details'),
        ),
    ]
