# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostYourAd', '0025_auto_20170422_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotbasisrooms',
            name='gender',
            field=models.CharField(blank=True, choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=20),
        ),
    ]
