# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostYourAd', '0026_auto_20170425_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotbasisrooms',
            name='room_rent_type',
            field=models.CharField(blank=True, choices=[(b'Y', b'Yearly'), (b'S', b'SemisterWise'), (b'M', b'Monthly')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cotbasisrooms',
            name='room_type',
            field=models.CharField(blank=True, choices=[(b'ONE', b'Single Room'), (b'TWO', b'Sharing With Another Student'), (b'THREE', b'Sharing With Other Two'), (b'FOUR', b'Sharing With Other Three')], max_length=100),
        ),
    ]
