# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostYourAd', '0027_auto_20170425_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatonrent',
            name='flat_type',
            field=models.CharField(choices=[(b'HallKitchen', b'HK'), (b'RoomKitchen', b'RK'), (b'1BHK', b'1BHK'), (b'2BHK', b'2BHK'), (b'3BHK', b'3BHK')], max_length=100),
        ),
        migrations.AlterField(
            model_name='flatonrent',
            name='furnishing_type',
            field=models.CharField(choices=[(b'U', b'UNFURNISHED'), (b'F', b'FULLY_FURNISHED'), (b'S', b'SEMI_FURNISHED')], max_length=100),
        ),
    ]
