# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAdministrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default=b'some string', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='contact_no',
            field=models.CharField(default=b'some string', max_length=10),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default=b'some string', max_length=200),
        ),
    ]
